#!/usr/bin/env bash

export PYTHON_EGG_CACHE=/srv/trac/sage_trac/.egg-cache

MASTER_BRANCH=develop

while read oldrev newrev refname; do
    if [ "$newrev" == "0000000000000000000000000000000000000000" ]; then
        continue
    fi
    if [ "$oldrev" == "0000000000000000000000000000000000000000" ]; then
        git rev-list --reverse $newrev ^$MASTER_BRANCH
    else
        git rev-list --reverse $newrev ^$oldrev ^$MASTER_BRANCH
    fi |
    while read rev; do
        sudo -u www-data /usr/local/bin/trac-admin /srv/trac/sage_trac changeset added '(default)' $rev
    done
done
